name: AutoBuild
on:
  push:
    branches: ["master", "dev"]
  pull_request:
    types:
      - opened
jobs:
  build_Windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Execute unit tests
      run: dotnet test
    - name: Build
      run: dotnet build WonderLab/WonderLabX.csproj --configuration Release -p:RuntimeIdentifier=win-x64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows
        path: WonderLab/bin/Release/net6.0
  build_Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Execute unit tests
      run: dotnet test
    - name: Build
      run: dotnet build WonderLab/WonderLabX.csproj --configuration Release -p:RuntimeIdentifier=linux-x64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux
        path: WonderLab/bin/Release/net6.0
  build_MacOS:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Execute unit tests
      run: dotnet test
    - name: Build
      run: dotnet build WonderLab/WonderLabX.csproj --configuration Release -p:RuntimeIdentifier=osx-x64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MacOS
        path: WonderLab/bin/Release/net6.0
  build_Linux_Deb:
    runs-on:  ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Execute unit tests
      run: dotnet test
    - name: Install Deb Tool
      run: dotnet tool install --global dotnet-deb
    - name: Build
      run: dotnet publish WonderLab/WonderLabX.csproj -c Release -r "linux-x64" -p:PublishSingleFile="false" -p:PublishReadyToRun=true -t:CreateDeb
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux_Deb
        path: 'WonderLab/bin/Release/net6.0/linux-x64/*.deb'
  build_Linux_Rpm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Execute unit tests
      run: dotnet test
    - name: Install Rpm Tool
      run: dotnet tool install --global dotnet-rpm
    - name: Build
      run: dotnet publish WonderLab/WonderLabX.csproj -c Release -r "linux-x64" -p:PublishSingleFile="false" -p:PublishReadyToRun=true -t:CreateRpm
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux_Rpm
        path: 'WonderLab/bin/Release/net6.0/linux-x64/*.rpm'
  build_Common:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Execute unit tests
      run: dotnet test
    - name: Build
      run: dotnet build WonderLab/WonderLabX.csproj --configuration Release
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Common
        path: WonderLab/bin/Release/net6.0
  Release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [build_Windows, build_MacOS, build_Linux_Deb, build_Linux_Rpm, build_Linux, build_Common]
    steps:
    - name: Download Windows Build
      uses: actions/download-artifact@v3
      with:
       name: Windows
       path: Release\Windows
    - name: Create Windows ZIP
      uses: thedoctor0/zip-release@0.7.1
      with:
         type: 'zip'
         filename: 'WonderLab_Windows.zip'
         path: 'Release\Windows'
    - name: Download Linux Build
      uses: actions/download-artifact@v3
      with:
       name: Linux
       path: Release\Linux
    - name: Create Linux ZIP
      uses: thedoctor0/zip-release@0.7.1
      with:
         type: 'zip'
         filename: 'WonderLab_Linux.zip'
         path: 'Release\Linux'
    - name: Download Deb Build
      uses: actions/download-artifact@v3
      with:
       name: Linux_Deb
    - name: Download Rpm Build
      uses: actions/download-artifact@v3
      with:
        name: Linux_Rpm
    - name: Download MacOS Build
      uses: actions/download-artifact@v3
      with:
       name: MacOS
       path: Release\MacOS
    - name: Create MacOS ZIP
      uses: thedoctor0/zip-release@0.7.1
      with:
         type: 'zip'
         filename: 'WonderLab_MacOS.zip'
         path: 'Release\MacOS'
    - name: Download Common Build
      uses: actions/download-artifact@v3
      with:
       name: Common
       path: Release\Common
    - name: Create Common ZIP
      uses: thedoctor0/zip-release@0.7.1
      with:
         type: 'zip'
         filename: 'WonderLab_Common.zip'
         path: 'Release\Common'

    - name: Create Release
      if: github.event_name != 'pull_request' 
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: AutoBuild
        title: "自动构建版本"
        files: |
            WonderLab_Common.zip
            WonderLab_Windows.zip
            WonderLab_Linux.zip
            WonderLab_MacOS.zip
            *.deb
            *.rpm
